### PR TITLE
Human help to regro-autotick-bot

### PR DESCRIPTION
**Pull request by sodre**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
FYI you can also just push to the bot's branch

**Comment by sodre** [comment]
In this case I can't because I am not in the fancycompleter team :( 

I am just trying to get a green-light to make it simpler to merge it when everything is taken care of.

**Comment by CJ-Wright** [comment]
Ah that is rough.

**Comment by sodre** [comment]
@CJ-Wright, are you able to merge fancycompleter yourself, it has been more than a week? I am willing to become a package comaintainer as well to make it go faster next time.

**Comment by CJ-Wright** [comment]
@conda-forge/fancycompleter could we get some review please?

**Comment by CJ-Wright** [comment]
@conda-forge/core thoughts?

**Comment by isuruf** [comment]
@CJ-Wright, any thoughts about giving write permissions to the bots repos to conda-forge/all-members ?

**Comment by CJ-Wright** [comment]
Hmm ok, what is the best way to do that?

**Comment by CJ-Wright** [comment]
(although for the record I wanted input from core because the maintainer hadn't acted for over a week)

**Comment by kynan** [comment]
Sorry for being unresponsive!

**Pull request merged**
